### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by Techmj** [team2059/Lunkwill#1]
- [x] increase tele-op speed
- [x] Camera offset in constants
- [x] remove "fudge factor" for wheels in constants
- [x] install webcam with raspberry pi, figure out a way to reduce latency (maybe with lower res?)
- [ ] recalibrate 3d pose photonvision
- [ ] minimum distance so that rotation is achieved with go to tag cmd?
- [ ] have rotate to 180 degrees relative to tag cmd before activating go to tag cmd? maybe make parallel?
- [ ] use GREEN LEDs with limelight, maybe try imaging raspi to photonvision/limelight software?
- [ ] implement negate gyro after auto
- [x] redo extend logic, make sure everything works with new design (no more ratchet)
- [x]  reduce by overlapping the arm movement with path-following for auto
- [ ] Test auto and balance with no FF
- [x] Faster drive in .drive()
- [ ] [2 element auto +taxi+ no balance (figure out zeroArmCmd  + toggle gripper and goToTag at end, goToTag proxy?)](https://photos.app.goo.gl/LCs8dkhXYJJycz736)
- [x] test transformTrajectoryForAlliance (make sure to select right auto on red alliance at comps)
- [x] test photonvision for 2023.4.1 LEDs
- [ ] Button to cancel current command
- [x] substation preset
- [x] Split arm cone presets into two steps
- [x] figure out gyro? -> make goToTag with current heading rather than resetting heading? 
- [x] originToFrontInches offset maybe decrease so goToTag hits bumpers
